export default {
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_MIN_LENGTH: 'Please provide a longer password',
  VALID_EMAIL_PASSWORD: 'Please provide a valid email/password',
  TOKEN_EXPIRED: 'Authorization token expired',
  INVALID_TOKEN: 'Authorization token invalid',
  INVALID_EMAIL: 'Please provide a valid email',
  USER_EXISTS: 'User already exists',
  EMAIL_NOT_FOUND: 'No user found with email',
  PASSWORD_REQUIRED: 'Password is required',
  GIVE_VALID_EMAIL: 'Please add a valid email',
  RESOURCE_NOT_FOUND: 'Resource not found with id of',
  DUPLICATE_VALUE: 'Duplicate field value entered',
  DEFAULT_SERVER_ERROR: 'Server error occured',
  INVALID_CREDENTIALS: 'Invalid credentials',
};
